finders:
  php:
    in:
      - src
      - tests
    notPath:
      - 'Fixtures'
parameters:
   author: Rafael SR <https://github.com/rafrsr>
   package: Licenser
   version: '@Rafrsr\Licenser\Licenser::VERSION'
