language: php

php:
  - 5.9
  - 5.6
  - 7.0
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

install:
  - composer self-update
  - composer clear-cache
  - composer install --prefer-dist

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls